# Generated by Django 4.1.7 on 2023-04-15 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.IntegerField(validators=[django.core.validators.MaxValueValidator(22)])),
                ('price', models.IntegerField()),
                ('leftOnStock', models.IntegerField()),
            ],
        ),
    ]
