# Generated by Django 4.1.7 on 2023-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheelsmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
