# Generated by Django 4.1.7 on 2023-04-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelShop', '0002_wheelsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelsmodel',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
