# Generated by Django 4.2 on 2023-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelShop', '0003_alter_wheelsmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelShopBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basket', models.ManyToManyField(to='wheelShop.wheelsmodel')),
            ],
        ),
    ]
